server:
<<<<<<< HEAD
  port: 9100
=======
  port: 9000
>>>>>>> 6cef41841392685a32698ca62f6554d5060b5b2d

spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin

<<<<<<< HEAD
#logging:
#  config: classpath:log4j2-spring.xml
=======
logging:
  config: classpath:log4j2-spring.xml
>>>>>>> 6cef41841392685a32698ca62f6554d5060b5b2d

eureka:
  instance:
    appname: ${spring.application.name}
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    hostname: 127.0.0.1
  client:
<<<<<<< HEAD
    ###因为自己是为注册中心，不需要自己注册自己
    register-with-eureka: false
    ###因为自己是为注册中心，不需要检索服务
    fetch-registry: false

=======
    register-with-eureka: true
    fetch-registry: true
>>>>>>> 6cef41841392685a32698ca62f6554d5060b5b2d
    service-url:
      #      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@10.3.212.35:${server.port}/eureka/
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:${server.port}/eureka/
  server:
    peer-node-read-timeout-ms: 500