
server:
  port: 9250
  servlet:
    context-path: /

spring:
  security:
    user:
      password: admin
      name: admin
  application:
    name: user-api
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://180.76.149.24:3306/mas_test1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: baidu-mysql
    password: 12345678

#eureka:
#  instance:
#    # 使用 ip 代替实例名
#    prefer-ip-address: true
#    # 实例的主机名
#    hostname: ${spring.cloud.client.ip-address}
#    # 实例的 ID 规则
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:9100/eureka/
#
#    #是否将服务注册到注册中心
#    register-with-eureka: true
#    #是否需要从注册中心获取服务注册信息
#    fetch-registry: true

eureka:
  instance:
    appname: ${spring.application.name}
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    hostname: 127.0.0.1
  client:
    service-url:
      #      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@10.3.212.35:${server.port}/eureka/
      #      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:9100/eureka/
      defaultZone: http://127.0.0.1:9100/eureka/
    ###是否将服务注册到注册中心
    register-with-eureka: true
    ###是否需要从注册中心获取服务注册信息
    fetch-registry: true
  server:
    peer-node-read-timeout-ms: 500
